### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by well0nez** [jernejsk/OpenELEC-OPi2#16]
Hey thanks for your efford. i love kodi

Could you have a look at here?

forum.kodi.tv/showthread.php?tid=258494

I'm searching for an advice.
Hope newer (kodi)-versions will faster available in openelecs build so you can merge em.
The new api changes a lot and would maybe more easier to modify.

another problem i do have with my wifi adapter (alfa, rtl8189).
i got an orange pi pc, the adapter is working mostly flawless. but the LED is not fully powered, and the download/upload speed is more than bad (2mbit), while in combination with my lap i get something around 80mbits..
maybe a shortener cable or a less consuming wireless stick?

another question would be at which speed are the cores runnning?
would be nice to know. i will get my heatsinks soon, so i wanna know if you
already overclocked it, or maybe there is some more place for more power.

thanks in advance.

**Comment by jernejsk** [comment]
I can't help you with your question on kodi forum.

So you are saying that WIFI is actually working? You can't compare WIFI on laptop and OPi. Usually wifi dongles offload work to main CPU which means that laptop will always be faster. Wifi dongles are usually not recommended for watching streams. Use ethernet cable. Speed there is around 10 MB/s, if you have good connection, like directly connection OPi and laptop.

CPU cores are running at 1200 MHz max. and I don't intend to overclock them. Due to HW support CPU has very little to do with video playback. You also don't need any heatsink, because temperatures are usually around 50C. Overclocking will just shorten device life.

Next time, use forum for questions.
