### ISSUE TITLE
cpufreq governor -> performance

### ISSUE THREAD

**Issue by seblucas** [jernejsk/OpenELEC-OPi2#48]
May I ask why the governor is set to performance ?

I tried changing it to conservative and of course the temperature went lower the UI still felt pretty great.

**Comment by jernejsk** [comment]
This is old setting, which helped when mali rendered video. I changed it to interactive, sam as Armbian.

**Comment by dhanar10** [comment]
@jernejsk Blindly changing the governor to interactive to match Armbian might be problematic.

I have an Orange Pi One running OpenELEC-H3.arm-7.0-devel-20160510194557-r22810-g4a963fc-opione.img.gz. The default governor is performance, but I changed it to interactive by writing to sysfs.

What I get is pulseaudio crackling. It does not happen on all videos but based on my observation, the issue can be triggered reliably using 720p H264 anime with ASS subtitle. Crackling will start about 5-10 minute into playback. My guess is pulseaudio is losing sync with the video and unable to get back in sync due to the interactive governor. 

Somehow, setting the governor to ondemand will make the issue dissapear.

**Comment by seblucas** [comment]
I have to say I'm a big fan of conservative for media players. my Nano pi gets hotter but so far it's been working fine

**Comment by jernejsk** [comment]
I certainly didn't blind copy this setting. I read through this issue https://github.com/igorpecovnik/lib/issues/298 and check few other articles as well.

BTW, so you are using bluetooth audio? Otherwise PulseAudio should not be used...

**Comment by dhanar10** [comment]
@jernejsk No. I am using HDMI output. 

I thought when Pulseaudio is running Kodi will always use it? Besides, AFAIK Pulseaudio will "bite" the ALSA device so that no other application can use it. If those applications want to output sound, they have to do it through Pulseaudio. 

I have already using Linux desktop even before Pulseaudio exist. So, I saw all kinds of problem during ALSA -> Pulseaudio transition, including crackling sound. That's why I suspect this crackling sound is related to Pulseaudio. I never experience crackling sound with ALSA.

**Comment by dhanar10** [comment]
@seblucas I will try to use conservative now and see whether the crackling sound issue appears. My understanding is that conservative is similar to ondemand but less aggresive.

**Comment by dhanar10** [comment]
@seblucas Conservative governor seems ok too. I did not get any sound crackling on my limited testing.

**Comment by jernejsk** [comment]
I discovered some severe issues because of enabled tv out. Please pull latest code and be sure to rebuild kernel package, which should take care for updating fex file. Then build new image and test your issues.

**Comment by dhanar10** [comment]
@jernejsk I tested OpenELEC-H3.arm-7.0-devel-20160602225329-r22840-g4575bc2 on my Orange Pi One and I cannot reproduce the sound crackling issue anymore on the new default "interactive" scaling governor. Nice.
