### ISSUE TITLE
A20 miniX

### ISSUE THREAD

**Issue by John677** [jernejsk/OpenELEC-OPi2#54]
Hello!
I new there)
Can you add device miniX A20 (h34) to this devices tree?

**_Specs:_**

```
Cpu: A20
Gpu: Mali400
Store: 4Gb
USB: 1 OTG: 1
Ir receiver
HDMI out
Wifi: 8192cu
```

Annnd here is script.fex of this device
[script.txt](https://github.com/jernejsk/OpenELEC-OPi2/files/267926/script.txt)

Strongly do not beat if I do not get there)

**Comment by seblucas** [comment]
I think only H3 are supported by this project.

A20 are kind of supported with Kodi with [this post](http://forum.kodi.tv/showthread.php?tid=254202)

**Comment by jernejsk** [comment]
As seblucas said, this project is only for H3, although it could be extended to other chips with DE 2.0. Unfortunately, A20 is none of the above. I would recommend the same Kodi thread as seblucas. Somewhere in the comments I saw also link to OpenELEC build but I didn't test it because I don't own A20 HW.
