### ISSUE TITLE
Can you fix the overscan issue also add some WiFi drivers?

### ISSUE THREAD

**Issue by fisherguy** [jernejsk/OpenELEC-OPi2#6]
@jernej It works great. No green stripe anymore. Only issues are reported below. 
1. One CPU stays 100%, cause by systemd?
2. Overscan issue which cannot see the whole screen.
And one request. @jernej, can you add rtl8188eus, rtl8188cus, MT7601 drivers to this Openelec build? I use USB wifi dongle to connect to internet. I can use it on Debian Jessie and Lubuntu. Care to add these three drivers?
MT7601 driver how to can check below link.
http://www.orangepi.org/orangepibbsen/forum.php?mod=redirect&goto=findpost&ptid=495&pid=5667&fromuid=37174

**Comment by jernejsk** [comment]
Please give me the link for video with overscan issue.

About other questions, 100% CPU is known issue which is caused by kernel somehow. Research on this is ongoing. I will take a look what can be done about wifi drivers, but don't hope too much. Some drivers are disabled because build fails and other requires some work. As someone already suggested on the forum, you are far better using ethernet cable for internet connection, because wifi is most of the time slow (even that built in OPi2).

**Comment by jernejsk** [comment]
Can you try latest code and tell me which of those issues exists? MT7601 is not there but other issues should be solved more or less.

**Comment by jernejsk** [comment]
I added driver for MT7601. I will consider this issue as fixed. If you still have problems, reopen it.
