### ISSUE TITLE
CEC support

### ISSUE THREAD

**Issue by vask3n** [jernejsk/OpenELEC-OPi2#68]
Hi Jernejsk,

I've compiled a OPiPC build yesterday because I saw commit's for CEC support being made but couldn't get it to work on my OrangePi. Is CEC support unfinished maybe?

Regards

**Comment by jernejsk** [comment]
It should work to some degree. Some says it's working perfectly and others that it doesn't work very well. I really don't have much overview over this because I currently don't own any CEC capable device. You should ask original author any specific questions: https://github.com/jodamm/linux/tree/sun8i
