### ISSUE TITLE
Resolution support?

### ISSUE THREAD

**Issue by Kestranor** [jernejsk/OpenELEC-OPi2#89]
Hi Jernej!

I'm asking this here because I tried to go through the mega-thread on the OPi forums, but only found partial information. I'm trying to get the latest prebuilt image working with a display that has a native resolution of 1280x1024. Therefore, I changed the script.bin using sunxi tools to the following settings:
[disp_init]
disp_init_enable = 1
disp_mode = 0
screen0_output_type = 3
screen0_output_mode = 5
screen1_output_type = 0
screen1_output_mode = 0
fb0_format = 0
fb0_width = 1280
fb0_height = 1024
fb1_format = 0
fb1_width = 0
fb1_height = 0

I also tried without setting the width and height, but the result is the same: my display says the resolution is not supported. I'm using a HDMI-VGA converter by the way, to connect the OPi PC to the monitor.
According to the info I found, this resolution might not even be supported by OpenElec, but that info is fairly old. Is this still the case? Also, I've read something about you experimenting with an EDID implementation, but I'm not sure if you managed to get it working or not.
In any case, is it possible to use a monitor with this resolution (even in 1280x720 if possible) or is it hopeless?

Thanks in advance.

**Comment by jernejsk** [comment]
As you may noticed, development of this stopped a long time ago. More or less all informations found on that mega thread are still true, including that only few resolutions are supported. 1280x1024 isn't supported.

Arbitrary resolution support works on LibreELEC, but port it's not very useful yet. Since LE port is based on mainline kernel, HW decoding doesn't work yet. It should in a few months.

I have no intention of updating this project anymore, LE will superseed it soon.

**Comment by Kestranor** [comment]
Right. Thanks for clarifying it. I'll keep checking back on LibreELEC in that case.
