### ISSUE TITLE
Orange Pi 2 is Orange PI pc 2?

### ISSUE THREAD

**Issue by manel00** [jernejsk/OpenELEC-OPi2#90]
Hi!

I'd like to know what is Orange Pi 2: 

Orange pi pc 2 or Orange pi plus 2?

In case of there's no image for ORange pi pc 2... could I ask for when does it will be created?

Thank you very much

**Comment by jernejsk** [comment]
Orange Pi 2 is this: http://linux-sunxi.org/Xunlong_Orange_Pi_2

Since Orange Pi PC 2 is based on H5 SoC, it's not supported by this project and never will be. However, I'm working on support for H5 based boards in LibreELEC, which are based on mainline kernel. However, main functionality is missing - HW accelerated decoding (it should be implemented later this year).

Because of all that, currently Android + Kodi is best combination for H5 based SBCs until HW accelerated decoding becomes supported in mainline kernel.

BTW, this project is not developed anymore for some time now. I'll lock it to be more apparent.
